name: First Scraper

# On means when will the action be triggered
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      #first we need to clone our repo onto the blank computer, so it can execute our code!
      - name: Checkout
        uses: actions/checkout@v4
        #uses tells it that you're using a marketplace step

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          #the documentation will list how to install other languages, too
       
      - name: Install scraper
        run: pip install warn-scraper

      - name: Scrape
        run: warn-scraper ia --data-dir ./data/
        #--data-dir specifies the data directory that the data is being sent to

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add ./data/
          git commit -m "Latest data for Iowa" && git push || true
